// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _02_Exam_Social_Network.Data;

#nullable disable

namespace _02_Exam_Social_Network.Migrations
{
    [DbContext(typeof(SNetworkDbContext))]
    [Migration("20250827155744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_02_Exam_Social_Network.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rubelmaksum2404@gmail.com",
                            Name = "Maksym",
                            Password = "TestPass22"
                        },
                        new
                        {
                            Id = 2,
                            Email = "rubelmaksum1@gmail.com",
                            Name = "Igor",
                            Password = "TestPass22"
                        },
                        new
                        {
                            Id = 3,
                            Email = "rubelmaksum2@gmail.com",
                            Name = "Denys",
                            Password = "TestPass22"
                        },
                        new
                        {
                            Id = 4,
                            Email = "rubelmaksum3@gmail.com",
                            Name = "Petya",
                            Password = "TestPass22"
                        },
                        new
                        {
                            Id = 5,
                            Email = "rubelmaksum4@gmail.com",
                            Name = "Vika",
                            Password = "TestPass22"
                        },
                        new
                        {
                            Id = 6,
                            Email = "rubelmaksum5@gmail.com",
                            Name = "Katya",
                            Password = "TestPass22"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
